/* =====================================================================
   CATÁLOGO DE PRODUTOS
   ---------------------------------------------------------------------
   Para ADICIONAR um produto: copie um bloco { ... }, cole no final da
   lista (antes do "];"), troque as informações e salve.
   Para TIRAR do site: apague o bloco, ou acrescente  visivel: false,

   Campos:
     id            → nome único, sem espaço nem acento (ex: "toledo-prix-4-uno")
     nome          → nome do produto
     marca         → fabricante
     categoria     → "balancas" | "automacao" | "informatica"
     subcategoria  → uma das subcategorias listadas em CATEGORIAS abaixo
     resumo        → frase curta que aparece no card
     descricao     → texto maior que aparece nos detalhes
     especificacoes→ lista de ["Nome", "Valor"] (pode deixar [])
     imagem        → nome do arquivo em compartilhado/img/produtos/
     estoque       → "consulte"   (Consulte disponibilidade — padrão)
                     "disponivel" (Pronta entrega)
                     "encomenda"  (Sob encomenda)
                     "esgotado"   (Esgotado)
     condicao      → "novo" | "seminovo"
     preco         → "" para não mostrar preço, ou ex: "R$ 2.490,00 à vista"
     destaque      → true para aparecer na página inicial
     visivel       → (opcional) false esconde o produto sem apagar

   Todos os produtos começam como "consulte" (Consulte disponibilidade).
   Se quiser destacar algo que está na loja, troque para "disponivel".
   ===================================================================== */

window.CATEGORIAS = [
  {
    id: "balancas",
    nome: "Balanças",
    descricao: "Comerciais, com impressora de etiquetas, industriais, de checkout e hospitalares.",
    subcategorias: ["Com impressora de etiquetas", "Computadoras", "Pesadoras", "Checkout", "Industriais e conferência", "Médico-hospitalar"]
  },
  {
    id: "automacao",
    nome: "Automação Comercial",
    descricao: "Impressoras de etiquetas, leitores, gavetas, terminais, fatiadores e mídia digital.",
    subcategorias: ["Impressoras de etiquetas", "Leitores de código de barras", "Gavetas de dinheiro", "Terminais de consulta", "Teclados e microterminais", "Fatiadores", "Tabelas digitais"]
  },
  {
    id: "informatica",
    nome: "Informática e PDV",
    descricao: "Computadores para PDV, impressoras de cupom, emissores fiscais e nobreaks.",
    subcategorias: ["Computadores", "Impressoras de cupom", "Emissores fiscais (SAT)", "Nobreaks"]
  }
];

window.PRODUTOS = [

  /* ----------------------------- BALANÇAS ----------------------------- */
  {
    id: "toledo-prix-4-uno",
    nome: "Prix 4 Uno",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Com impressora de etiquetas",
    resumo: "Balança com impressora de etiquetas para balcão de frios, açougue e padaria.",
    descricao: "Pesa, calcula o preço e imprime etiquetas com código de barras lidas direto no caixa. Ideal para padarias, açougues, rotisserias e hortifrútis que querem agilidade no atendimento.",
    especificacoes: [["Capacidade", "15 kg"], ["Impressão", "Etiquetas térmicas com código de barras"], ["Indicada para", "Padarias, açougues e frios"]],
    imagem: "prix4uno.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "toledo-prix-4-due",
    nome: "Prix 4 Due",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Com impressora de etiquetas",
    resumo: "Balança com impressora de etiquetas, 30 kg, para alto volume de pesagens.",
    descricao: "Balança computadora com impressora de etiquetas para setores de grande movimento, como açougues, padarias e seções de frios de supermercados.",
    especificacoes: [["Capacidade", "30 kg"], ["Impressão", "Etiquetas térmicas com código de barras"], ["Indicada para", "Supermercados e açougues"]],
    imagem: "prix4due.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-prix-5-plus",
    nome: "Prix 5 Plus",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Com impressora de etiquetas",
    resumo: "Balança com impressora de etiquetas e teclado completo de produtos.",
    descricao: "Modelo robusto da linha Prix com impressora de etiquetas, teclado amplo para cadastro rápido de produtos e display de fácil leitura para operador e cliente.",
    especificacoes: [["Capacidade", "30 kg"], ["Impressão", "Etiquetas térmicas com código de barras"], ["Indicada para", "Supermercados, padarias e frios"]],
    imagem: "prix5.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "balmak-orion-1-plus",
    nome: "Orion 1 Plus",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Com impressora de etiquetas",
    resumo: "Balança com impressora de etiquetas, 30 kg, ótimo custo-benefício.",
    descricao: "Balança computadora com impressora de etiquetas da Balmak. Imprime etiquetas com código de barras para leitura direta no PDV, com teclado de produtos e display para operador e cliente.",
    especificacoes: [["Capacidade", "30 kg"], ["Impressão", "Etiquetas térmicas com código de barras"], ["Indicada para", "Padarias, açougues e hortifrútis"]],
    imagem: "balmak.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "balmak-orion-2",
    nome: "Orion 2",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Com impressora de etiquetas",
    resumo: "Balança com impressora de etiquetas, versões com torre e de balcão.",
    descricao: "Linha Orion 2 da Balmak, com impressora de etiquetas, disponível em versão de balcão e com torre de display elevado.",
    especificacoes: [["Capacidade", "30 kg"], ["Impressão", "Etiquetas térmicas com código de barras"]],
    imagem: "balmak-orion2.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-prix-3-fit",
    nome: "Prix 3 Fit",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Computadoras",
    resumo: "Pesa e calcula o preço na hora. Compacta e precisa.",
    descricao: "Balança computadora (pesa e calcula preço) da Toledo, ideal para feiras, hortifrútis, docerias e pequenos comércios.",
    especificacoes: [["Capacidade", "15 kg"], ["Função", "Pesa e calcula o preço"], ["Indicada para", "Hortifrútis e pequenos comércios"]],
    imagem: "prix3fit.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "toledo-prix-3-plus",
    nome: "Prix 3 Plus",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Computadoras",
    resumo: "Balança computadora com display para operador e cliente.",
    descricao: "Balança que pesa e calcula o preço, com displays para operador e cliente. Robusta, com prato em aço inox.",
    especificacoes: [["Função", "Pesa e calcula o preço"], ["Prato", "Aço inox"]],
    imagem: "prix3plus.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "balmak-one",
    nome: "ONE",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Computadoras",
    resumo: "Balança computadora 15/30 kg, design moderno.",
    descricao: "Balança computadora da Balmak que pesa e calcula preço, com visual moderno e displays de fácil leitura.",
    especificacoes: [["Capacidade", "15 kg ou 30 kg"], ["Função", "Pesa e calcula o preço"]],
    imagem: "balmak-one.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-9094-plus",
    nome: "9094 Plus",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Pesadoras",
    resumo: "Balança pesadora para balcão e integração com o caixa.",
    descricao: "Balança pesadora Toledo para balcões e caixas, indicada para conferência de peso e integração com o sistema de vendas.",
    especificacoes: [["Função", "Pesadora"]],
    imagem: "9094plus.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "balmak-one-pesadora",
    nome: "ONE Pesadora",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Pesadoras",
    resumo: "Pesadora simples e precisa para o dia a dia.",
    descricao: "Versão pesadora da linha ONE da Balmak, ideal para balcões e conferência de mercadorias.",
    especificacoes: [["Função", "Pesadora"]],
    imagem: "one-pesadora.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-8217",
    nome: "8217 Checkout",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Checkout",
    resumo: "Balança de checkout para caixas de supermercado.",
    descricao: "Balança para embutir no checkout, integrada ao PDV para pesagem direta no caixa.",
    especificacoes: [["Capacidade", "30 kg"], ["Instalação", "Embutida no checkout"]],
    imagem: "8217.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "balmak-bck30",
    nome: "BCK30 Checkout",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Checkout",
    resumo: "Balança de checkout 30 kg integrada ao PDV.",
    descricao: "Balança de checkout da Balmak para pesagem no caixa, integrada ao sistema de vendas.",
    especificacoes: [["Capacidade", "30 kg"], ["Instalação", "Checkout / caixa"]],
    imagem: "bck30.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-2098",
    nome: "2098 Plataforma",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Industriais e conferência",
    resumo: "Balança de plataforma para indústria, depósito e conferência.",
    descricao: "Linha de balanças de plataforma Toledo para recebimento de mercadorias, conferência e uso industrial.",
    especificacoes: [["Capacidade", "até 300 kg"], ["Uso", "Indústria, depósito e conferência"]],
    imagem: "2098.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "balmak-w300",
    nome: "Plataforma 300 kg",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Industriais e conferência",
    resumo: "Balança de plataforma 300 kg com indicador digital.",
    descricao: "Balança de plataforma robusta para recebimento, expedição e conferência de mercadorias.",
    especificacoes: [["Capacidade", "300 kg"], ["Uso", "Indústria, depósito e conferência"]],
    imagem: "w300.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-hospitalar",
    nome: "Balança Hospitalar",
    marca: "Toledo",
    categoria: "balancas",
    subcategoria: "Médico-hospitalar",
    resumo: "Balança digital para farmácias, clínicas e hospitais.",
    descricao: "Balança médica digital com coluna, para farmácias, clínicas, consultórios e hospitais.",
    especificacoes: [["Uso", "Farmácias, clínicas e hospitais"]],
    imagem: "hospitalar.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "balmak-bk200f",
    nome: "BK-200F",
    marca: "Balmak",
    categoria: "balancas",
    subcategoria: "Médico-hospitalar",
    resumo: "Balança digital 200 kg para farmácias e clínicas.",
    descricao: "Balança digital Balmak para farmácias, academias e clínicas, com capacidade de 200 kg.",
    especificacoes: [["Capacidade", "200 kg"], ["Uso", "Farmácias, academias e clínicas"]],
    imagem: "bk200f.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },

  /* ------------------------- AUTOMAÇÃO COMERCIAL ------------------------- */
  {
    id: "elgin-l42-pro",
    nome: "L42 Pro",
    marca: "Elgin",
    categoria: "automacao",
    subcategoria: "Impressoras de etiquetas",
    resumo: "Impressora de etiquetas para gôndola, produtos e logística.",
    descricao: "Impressora de etiquetas de mesa para etiquetas de gôndola, produtos, códigos de barras e expedição.",
    especificacoes: [["Tipo", "Impressora de etiquetas de mesa"]],
    imagem: "l42pro.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "argox-os-2140",
    nome: "OS-2140",
    marca: "Argox",
    categoria: "automacao",
    subcategoria: "Impressoras de etiquetas",
    resumo: "Impressora de etiquetas compacta e confiável.",
    descricao: "Impressora de etiquetas de mesa Argox, compacta e confiável para o dia a dia do comércio.",
    especificacoes: [["Tipo", "Impressora de etiquetas de mesa"]],
    imagem: "argox.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "zebra-zt230",
    nome: "ZT230",
    marca: "Zebra",
    categoria: "automacao",
    subcategoria: "Impressoras de etiquetas",
    resumo: "Impressora de etiquetas industrial para alta produção.",
    descricao: "Impressora industrial Zebra para produção de etiquetas em alto volume, ideal para indústrias e centros de distribuição.",
    especificacoes: [["Tipo", "Impressora de etiquetas industrial"]],
    imagem: "zebra.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "tanca-tl-120",
    nome: "TL-120",
    marca: "Tanca",
    categoria: "automacao",
    subcategoria: "Leitores de código de barras",
    resumo: "Leitor de código de barras de mão, USB.",
    descricao: "Leitor de código de barras de mão para caixas, estoque e conferência.",
    especificacoes: [["Tipo", "Leitor de mão"]],
    imagem: "tl120.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "tanca-tl-220",
    nome: "TL-220",
    marca: "Tanca",
    categoria: "automacao",
    subcategoria: "Leitores de código de barras",
    resumo: "Leitor de código de barras com suporte de mesa.",
    descricao: "Leitor de código de barras com suporte, para uso nas mãos ou apoiado no balcão do caixa.",
    especificacoes: [["Tipo", "Leitor de mão com suporte"]],
    imagem: "tl220.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "datalogic-quickscan-qw2100",
    nome: "QuickScan QW2100",
    marca: "Datalogic",
    categoria: "automacao",
    subcategoria: "Leitores de código de barras",
    resumo: "Leitor com suporte, leitura rápida e precisa.",
    descricao: "Leitor de código de barras com suporte de mesa, leitura rápida inclusive de códigos danificados.",
    especificacoes: [["Tipo", "Leitor de mão com suporte"]],
    imagem: "quickscan.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "elgin-el4200",
    nome: "EL4200",
    marca: "Elgin",
    categoria: "automacao",
    subcategoria: "Leitores de código de barras",
    resumo: "Leitor fixo para checkout, leitura em qualquer direção.",
    descricao: "Leitor de mesa para checkout: basta passar o produto em frente ao leitor, sem precisar posicionar o código.",
    especificacoes: [["Tipo", "Leitor fixo de checkout"]],
    imagem: "el4200.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "tanca-tl-900",
    nome: "TL-900",
    marca: "Tanca",
    categoria: "automacao",
    subcategoria: "Leitores de código de barras",
    resumo: "Leitor fixo de mesa para caixas de alto movimento.",
    descricao: "Leitor fixo de mesa para checkout, ideal para caixas com grande volume de vendas.",
    especificacoes: [["Tipo", "Leitor fixo de checkout"]],
    imagem: "tl900.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gaveta-menno",
    nome: "Gaveta de dinheiro",
    marca: "Menno",
    categoria: "automacao",
    subcategoria: "Gavetas de dinheiro",
    resumo: "Gaveta automática ou semiautomática para o caixa.",
    descricao: "Gaveta de dinheiro em aço, com abertura automática pela impressora ou semiautomática.",
    especificacoes: [["Abertura", "Automática ou semiautomática"]],
    imagem: "menno.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gaveta-bematech",
    nome: "Gaveta de dinheiro",
    marca: "Bematech",
    categoria: "automacao",
    subcategoria: "Gavetas de dinheiro",
    resumo: "Gaveta de dinheiro robusta para PDV.",
    descricao: "Gaveta de dinheiro Bematech para PDV, com abertura automática pela impressora ou semiautomática.",
    especificacoes: [["Abertura", "Automática ou semiautomática"]],
    imagem: "gavetabema.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gertec-tc504",
    nome: "Busca Preço TC504",
    marca: "Gertec",
    categoria: "automacao",
    subcategoria: "Terminais de consulta",
    resumo: "Terminal para o cliente consultar o preço sozinho.",
    descricao: "Terminal de consulta de preços para instalar no salão da loja: o cliente passa o código de barras e vê o preço na hora.",
    especificacoes: [["Tipo", "Terminal de consulta de preço"]],
    imagem: "gertec504.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gertec-g2",
    nome: "Busca Preço G2",
    marca: "Gertec",
    categoria: "automacao",
    subcategoria: "Terminais de consulta",
    resumo: "Terminal de consulta de preço compacto.",
    descricao: "Terminal compacto de consulta de preços para supermercados e lojas.",
    especificacoes: [["Tipo", "Terminal de consulta de preço"]],
    imagem: "gertecg2.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gertec-mt-720",
    nome: "Microterminal MT-720",
    marca: "Gertec",
    categoria: "automacao",
    subcategoria: "Teclados e microterminais",
    resumo: "Microterminal para lançamentos e comandas.",
    descricao: "Microterminal para lançamento de pedidos e comandas em bares, restaurantes e lanchonetes.",
    especificacoes: [["Tipo", "Microterminal"]],
    imagem: "mt720.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "gertec-tec-44",
    nome: "Teclado TEC 44",
    marca: "Gertec",
    categoria: "automacao",
    subcategoria: "Teclados e microterminais",
    resumo: "Teclado programável para agilizar o caixa.",
    descricao: "Teclado programável com teclas configuráveis para atalhos e produtos, agilizando as vendas no PDV.",
    especificacoes: [["Teclas", "44 programáveis"]],
    imagem: "tec44.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "smak-sko44",
    nome: "Teclado SKO44",
    marca: "Smak",
    categoria: "automacao",
    subcategoria: "Teclados e microterminais",
    resumo: "Teclado programável com display.",
    descricao: "Teclado programável para PDV com teclas configuráveis.",
    especificacoes: [["Tipo", "Teclado programável"]],
    imagem: "sko44.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-uni-350-ga",
    nome: "Fatiador Uni 350 GA",
    marca: "Toledo",
    categoria: "automacao",
    subcategoria: "Fatiadores",
    resumo: "Fatiador 100% automático em aço inox.",
    descricao: "Fatiador automático em aço inox para frios e embutidos, com alta produtividade e acabamento profissional.",
    especificacoes: [["Operação", "Automática"], ["Material", "Aço inox"]],
    imagem: "fatiador.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "toledo-uni-350",
    nome: "Fatiador Uni 350",
    marca: "Toledo",
    categoria: "automacao",
    subcategoria: "Fatiadores",
    resumo: "Fatiador semiautomático para frios.",
    descricao: "Fatiador semiautomático para frios e embutidos, ideal para padarias, mercearias e açougues.",
    especificacoes: [["Operação", "Semiautomática"], ["Material", "Aço inox"]],
    imagem: "uni350.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "toledo-mit",
    nome: "Tabela Digital MIT",
    marca: "Toledo",
    categoria: "automacao",
    subcategoria: "Tabelas digitais",
    resumo: "Preços, publicidade e senhas em TV.",
    descricao: "Solução de mídia digital para exibir tabela de preços, ofertas, publicidade e chamada de senhas em TVs.",
    especificacoes: [["Uso", "Preços, ofertas e senhas"]],
    imagem: "mit.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "balmak-all-midia",
    nome: "All Mídia",
    marca: "Balmak",
    categoria: "automacao",
    subcategoria: "Tabelas digitais",
    resumo: "Tabela digital de preços e publicidade.",
    descricao: "Tabela digital para exibir preços, publicidade e ofertas em TVs na sua loja.",
    especificacoes: [["Uso", "Preços, ofertas e publicidade"]],
    imagem: "allmidia.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },

  /* ------------------------- INFORMÁTICA E PDV ------------------------- */
  {
    id: "centrium-mini-pc",
    nome: "Mini PC para PDV",
    marca: "Centrium",
    categoria: "informatica",
    subcategoria: "Computadores",
    resumo: "Computador compacto completo, ideal para o caixa.",
    descricao: "Mini computador completo para frente de caixa: compacto, silencioso e eficiente para rodar o sistema de vendas.",
    especificacoes: [["Formato", "Mini PC"], ["Uso", "Frente de caixa"]],
    imagem: "centrium-pc.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "tanca-tp-650",
    nome: "TP-650",
    marca: "Tanca",
    categoria: "informatica",
    subcategoria: "Impressoras de cupom",
    resumo: "Impressora térmica de cupom com guilhotina.",
    descricao: "Impressora térmica não fiscal com guilhotina, para cupons, pedidos e comprovantes.",
    especificacoes: [["Tipo", "Térmica não fiscal"], ["Corte", "Guilhotina"], ["Conexão", "USB / Ethernet"]],
    imagem: "tanca.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "elgin-i9",
    nome: "i9",
    marca: "Elgin",
    categoria: "informatica",
    subcategoria: "Impressoras de cupom",
    resumo: "Impressora térmica de cupom rápida e confiável.",
    descricao: "Impressora térmica não fiscal com guilhotina, muito usada em PDVs, restaurantes e lanchonetes.",
    especificacoes: [["Tipo", "Térmica não fiscal"], ["Corte", "Guilhotina"]],
    imagem: "elgin-i9.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: true
  },
  {
    id: "epson-tm-t20",
    nome: "TM-T20",
    marca: "Epson",
    categoria: "informatica",
    subcategoria: "Impressoras de cupom",
    resumo: "Impressora térmica Epson com guilhotina.",
    descricao: "Impressora térmica não fiscal Epson, robusta e com guilhotina, para cupons e comprovantes.",
    especificacoes: [["Tipo", "Térmica não fiscal"], ["Corte", "Guilhotina"]],
    imagem: "epson-t20.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "sat-bematech-rb2000",
    nome: "SAT RB-2000",
    marca: "Bematech",
    categoria: "informatica",
    subcategoria: "Emissores fiscais (SAT)",
    resumo: "Equipamento SAT para emissão de CF-e.",
    descricao: "Equipamento SAT (CF-e). Atenção: em SP o CF-e SAT está proibido desde 01/01/2026 — fale com a gente para migrar para NFC-e.",
    especificacoes: [["Documento", "CF-e SAT"]],
    imagem: "bematech-sat.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false,
    visivel: false   // SAT proibido em SP desde 01/01/2026
  },
  {
    id: "sat-elgin-smart",
    nome: "SAT Smart",
    marca: "Elgin",
    categoria: "informatica",
    subcategoria: "Emissores fiscais (SAT)",
    resumo: "Equipamento SAT para emissão de CF-e.",
    descricao: "Equipamento SAT (CF-e). Atenção: em SP o CF-e SAT está proibido desde 01/01/2026 — fale com a gente para migrar para NFC-e.",
    especificacoes: [["Documento", "CF-e SAT"]],
    imagem: "elgin-smart.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false,
    visivel: false   // SAT proibido em SP desde 01/01/2026
  },
  {
    id: "sat-tanca-ts1000",
    nome: "SAT TS-1000",
    marca: "Tanca",
    categoria: "informatica",
    subcategoria: "Emissores fiscais (SAT)",
    resumo: "Equipamento SAT para emissão de CF-e.",
    descricao: "Equipamento SAT (CF-e). Atenção: em SP o CF-e SAT está proibido desde 01/01/2026 — fale com a gente para migrar para NFC-e.",
    especificacoes: [["Documento", "CF-e SAT"]],
    imagem: "sat-tanca.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false,
    visivel: false   // SAT proibido em SP desde 01/01/2026
  },
  {
    id: "nobreak-apc",
    nome: "Nobreak 400 VA",
    marca: "APC",
    categoria: "informatica",
    subcategoria: "Nobreaks",
    resumo: "Proteção para o PDV contra quedas de energia.",
    descricao: "Nobreak para proteger computador, impressora e balança contra quedas e oscilações de energia.",
    especificacoes: [["Potência", "400 VA"], ["Tensão", "Bivolt"]],
    imagem: "nobreak-apc.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  },
  {
    id: "nobreak-nhs",
    nome: "Nobreak 400 VA",
    marca: "NHS",
    categoria: "informatica",
    subcategoria: "Nobreaks",
    resumo: "Nobreak nacional robusto para o caixa.",
    descricao: "Nobreak NHS para proteger os equipamentos do caixa contra quedas e oscilações de energia.",
    especificacoes: [["Potência", "400 VA"], ["Tensão", "Bivolt"]],
    imagem: "nobreak-nhs.webp",
    estoque: "consulte",
    condicao: "novo",
    preco: "",
    destaque: false
  }
];
